# Generated by Django 4.0.6 on 2022-07-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='items',
            field=models.ManyToManyField(to='ads.ad'),
        ),
    ]
